# This file is automatically generated by scripts/generate_types.py
# Do not edit manually.

from typing import Any, TypedDict  # noqa: F401


class SafeExecTransactionParams(TypedDict):
    to: str
    value: int
    data: bytes
    operation: int
    safeTxGas: int
    baseGas: int
    gasPrice: int
    gasToken: str
    refundReceiver: str
    signatures: bytes


class SafeApproveHashParams(TypedDict):
    hashToApprove: bytes


class SafeGetTransactionHashParams(TypedDict):
    to: str
    value: int
    data: bytes
    operation: int
    safeTxGas: int
    baseGas: int
    gasPrice: int
    gasToken: str
    refundReceiver: str
    _nonce: int


class SafeRequiredTxGasParams(TypedDict):
    to: str
    value: int
    data: bytes
    operation: int
    safeTxGas: int
    baseGas: int
    gasPrice: int
    gasToken: str
    refundReceiver: str
    signatures: bytes


class SafeIsOwnerParams(TypedDict):
    owner: str


class SafeSetupParams(TypedDict):
    _owners: list[str]
    _threshold: int
    to: str
    data: bytes
    fallbackHandler: str
    paymentToken: str
    payment: int
    paymentReceiver: str


class SafeAddOwnerWithThresholdParams(TypedDict):
    owner: str
    _threshold: int


class SafeRemoveOwnerParams(TypedDict):
    prevOwner: str
    owner: str
    _threshold: int


class SafeSwapOwnerParams(TypedDict):
    prevOwner: str
    oldOwner: str
    newOwner: str


class SafeChangeThresholdParams(TypedDict):
    _threshold: int


class SafeEnableModuleParams(TypedDict):
    module: str


class SafeDisableModuleParams(TypedDict):
    prevModule: str
    module: str


class SafeGetModulesPaginatedParams(TypedDict):
    start: str
    pageSize: int


class SafeIsModuleEnabledParams(TypedDict):
    module: str


class SafeCheckSignaturesParams(TypedDict):
    dataHash: bytes
    data: bytes
    signatures: bytes


class SafeSetGuardParams(TypedDict):
    guard: str


class SafeSetFallbackHandlerParams(TypedDict):
    handler: str


class SafeProxyFactoryCreateProxyWithNonceParams(TypedDict):
    _singleton: str
    initializer: bytes
    saltNonce: int


class SafeProxyFactoryCreateChainSpecificProxyWithNonceParams(TypedDict):
    _singleton: str
    initializer: bytes
    saltNonce: int


class SafeProxyFactoryCreateProxyWithCallbackParams(TypedDict):
    _singleton: str
    initializer: bytes
    saltNonce: int
    callback: str


class Erc20TransferParams(TypedDict):
    _to: str
    _value: int


class Erc721SafeTransferFromParams(TypedDict):
    from_: str
    to: str
    tokenId: int


class Erc721TransferFromParams(TypedDict):
    from_: str
    to: str
    tokenId: int
